# Generated by Django 4.1.7 on 2023-03-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post_downvotes_post_upvotes_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='value',
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_type',
            field=models.CharField(choices=[('U', 'Upvote'), ('D', 'Downvote')], default='U', max_length=1),
        ),
    ]
